### ISSUE TITLE
Local problems

### ISSUE THREAD

**Issue by FranSua398** [roberthgnz/ko-dev#1]
Hi I tried to run this locally, but a lot of things fail in the supabase DB, could you add a SQL to create the tables? Or something that allows us to run it locally

**Comment by ryanadams20** [comment]
+1

**Comment by roberthgnz** [comment]
Hello @ryanadams20 @FranSua398 

I have uploaded the database schema together with the security policies, you can see it here. 

https://github.com/roberthgnz/ko-dev/blob/main/schema.sql
